development: &default
  adapter: postgresql
  encoding: unicode
  database: gematic-api_development
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME', 'gematic-api') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'gematic-api') %>
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>

test: &test
  <<: *default
  database: gematic-api_test

production:
  database: gematic-api_production
  adapter: postgresql
  encoding: unicode
  pool: 50
  url: <%= ENV['DATABASE_URL'] %>
